# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Will Doyle
url:                 http://wdoyle42.github.io
paginate:            1
baseurl:             http://wdoyle42.github.io

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Will Doyle
  url:               http://wdoyle42@github.io
  email:             w.doyle@vanderbilt.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/wdoyle42

# Navigation
pages_list:       
  About: '/about'